const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SET_FOLLOWER = 'SET_FOLLOWERS';
const SET_FOLLOWING = 'SET_FOLLOWING';
const SET_REPO = 'SET_REPO';
const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export {
  SET_CURRENT_USER,
  SET_FOLLOWER,
  SET_FOLLOWING,
  SET_REPO,
  REMOVE_CURRENT_USER
};
