import {
  SET_CURRENT_USER,
  SET_FOLLOWER,
  SET_FOLLOWING,
  SET_REPO,
  REMOVE_CURRENT_USER
} from '../User/constants';

const ADD_ERROR = 'ADD_ERROR';
const REMOVE_ERROR = 'REMOVE_ERROR';
const SET_LOADING = 'SET_LOADING';
const REMOVE_LOADING = 'REMOVE_LOADING';

export {
  ADD_ERROR,
  REMOVE_ERROR,
  SET_LOADING,
  REMOVE_LOADING,
  SET_CURRENT_USER,
  SET_FOLLOWER,
  SET_FOLLOWING,
  SET_REPO,
  REMOVE_CURRENT_USER
};
