const SETCURRENTUSER = "SET_CURRENT_USER";
const ADDERROR = "ADD_ERROR";
const REMOVEERROR = "REMOVE_ERROR";
const SETLOADING = "SET_LOADING";
const REMOVELOADING = "REMOVE_LOADING";
const SETFOLLOWER = "SET_FOLLOWERS";
const SETFOLLOWING = "SET_FOLLOWING";
const SETREPO = "SET_REPO";

export {
  SETCURRENTUSER,
  ADDERROR,
  REMOVEERROR,
  SETLOADING,
  REMOVELOADING,
  SETFOLLOWER,
  SETFOLLOWING,
  SETREPO
};
